class LOTClassConfig:
    def __init__(self,
        dataset_dir=None,
        overwrite_dataset=False,
        label_names_file="label_names.txt",
        pretrained_lm="camembert-base",
        train_file="train.txt",
        test_file=None,
        test_label_file=None,
        final_model="final_model.pt",
        out_file="out.txt",
        eval_batch_size=128,
        train_batch_size=32,
        top_pred_num=50,
        category_vocab_size=100,
        match_threshold=20,
        max_len=512,
        update_interval=50,
        accum_steps=1,
        mcp_epochs=3,
        self_train_epochs=1,
        early_stop=True,
        gpus=3,
        verbose=False,
        dist_port=12345):
    
        self.dataset_dir = dataset_dir
        self.overwrite_dataset = overwrite_dataset
        self.label_names_file = label_names_file
        self.pretrained_lm = pretrained_lm
        self.train_file = train_file
        self.test_file = test_file
        self.test_label_file = test_label_file
        self.final_model = final_model
        self.out_file = out_file
        self.eval_batch_size = eval_batch_size
        self.train_batch_size = train_batch_size
        self.top_pred_num = top_pred_num
        self.category_vocab_size = category_vocab_size
        self.match_threshold = match_threshold
        self.max_len = max_len
        self.update_interval = update_interval
        self.accum_steps = accum_steps
        self.mcp_epochs = mcp_epochs
        self.self_train_epochs = self_train_epochs
        self.early_stop = early_stop
        self.gpus = gpus
        self.dist_port = dist_port
        self.verbose = verbose
        self.mlm = True
